### ISSUE TITLE
PersistentUVShadow.setMission crashes when UV Hub receives MISSION_ACK

### ISSUE THREAD

**Issue by envirover** [envirover/UVHub#113]
when RadioRoom sends MISSION_ACK on UVHUB this is the following log error on UVHUB

uvhub_1     | 2021-03-12 14:30:41 INFO  RR/TCP >> MISSION_ACK: compid=1, sysid=1, target_system=250, target_component=1, type=1
uvhub_1     | 2021-03-12 14:30:41 ERROR state should be: writes is not an empty list
uvhub_1     | java.lang.IllegalArgumentException: state should be: writes is not an empty list
uvhub_1     |   at com.mongodb.assertions.Assertions.isTrueArgument(Assertions.java:99) ~[mongo-java-driver-3.12.0.jar:?]
uvhub_1     |   at com.mongodb.operation.MixedBulkWriteOperation.<init>(MixedBulkWriteOperation.java:113) ~[mongo-java-driver-3.12.0.jar:?]
uvhub_1     |   at com.mongodb.internal.operation.Operations.insertMany(Operations.java:385) ~[mongo-java-driver-3.12.0.jar:?]
uvhub_1     |   at com.mongodb.internal.operation.SyncOperations.insertMany(SyncOperations.java:205) ~[mongo-java-driver-3.12.0.jar:?]
uvhub_1     |   at com.mongodb.client.internal.MongoCollectionImpl.executeInsertMany(MongoCollectionImpl.java:529) ~[mongo-java-driver-3.12.0.jar:?]
uvhub_1     |   at com.mongodb.client.internal.MongoCollectionImpl.insertMany(MongoCollectionImpl.java:513) ~[mongo-java-driver-3.12.0.jar:?]
uvhub_1     |   at com.mongodb.client.internal.MongoCollectionImpl.insertMany(MongoCollectionImpl.java:508) ~[mongo-java-driver-3.12.0.jar:?]
uvhub_1     |   at com.envirover.uvnet.shadow.impl.PersistentUVShadow.setMission(PersistentUVShadow.java:254) ~[uvnet-2.4.0.jar:?]
uvhub_1     |   at com.envirover.uvhub.MOMessageHandler.handleMessage(MOMessageHandler.java:288) ~[uvhub-2.4.0.jar:?]
uvhub_1     |   at com.envirover.uvhub.RRTcpServer$SocketListener.run(RRTcpServer.java:172) [uvhub-2.4.0.jar:?]
uvhub_1     |   at java.lang.Thread.run(Thread.java:830) [?:?]

**Comment by gab933** [comment]
Hi Pavel,
I think the problem is caused by the following line inside MOMessageHandler.java

shadow.setMission(mission_ack.sysid, shadow.getDesiredMission());

I'll investigate better about the specific cause of the problem.
Gabriele
